// Core/Learning/SuggestionApprovalManager.swift
import Foundation

/// SuggestionApprovalManager handles approval and decline of suggestions generated by SuggestionGenerator.
/// It applies changes (via DeviationDetector) or dismisses suggestions and stores decision history.
public final class SuggestionApprovalManager: @unchecked Sendable {
    
    // MARK: - Singleton
    
    public static let shared = SuggestionApprovalManager()
    
    // MARK: - Properties
    
    private let suggestionGenerator = SuggestionGenerator.shared
    private let deviationDetector = DeviationDetector.shared
    private let database = DatabaseManager.shared
    private let logger = Logger.shared
    
    /// Lock for thread-safe operations
    private let lock = NSLock()
    
    // MARK: - Initialization
    
    private init() {
        initializeDecisionTable()
    }
    
    /// Ensure the decision history table exists
    private func initializeDecisionTable() {
        do {
            try database.createDecisionHistoryTableIfNeeded()
        } catch {
            logger.error("Failed to initialize decision history table: \(error.localizedDescription)")
        }
    }
    
    // MARK: - Main Actions
    
    /// Approve a suggestion - applies the suggested change
    /// - Parameter suggestion: The suggestion to approve
    /// - Returns: Result indicating success or failure with details
    public func approveSuggestion(_ suggestion: Suggestion) -> ApprovalResult {
        lock.lock()
        defer { lock.unlock() }
        
        logger.info("Approving suggestion: \(suggestion.id)")
        
        do {
            // Apply the suggestion based on its type
            let result = try applySuggestion(suggestion)
            
            // Store the decision in history
            let decision = SuggestionDecision(
                suggestionId: suggestion.id,
                suggestionType: suggestion.type,
                decision: .approved,
                timestamp: Date(),
                suggestionMessage: suggestion.message
            )
            
            try database.saveDecision(decision)
            
            logger.info("Successfully approved suggestion: \(suggestion.id)")
            return .success(result)
        } catch {
            logger.error("Failed to approve suggestion: \(error.localizedDescription)")
            return .failure(error.localizedDescription)
        }
    }
    
    /// Decline a suggestion - dismisses without applying
    /// - Parameter suggestion: The suggestion to decline
    /// - Returns: Result indicating success or failure
    public func declineSuggestion(_ suggestion: Suggestion) -> ApprovalResult {
        lock.lock()
        defer { lock.unlock() }
        
        logger.info("Declining suggestion: \(suggestion.id)")
        
        do {
            // Store the decision in history
            let decision = SuggestionDecision(
                suggestionId: suggestion.id,
                suggestionType: suggestion.type,
                decision: .declined,
                timestamp: Date(),
                suggestionMessage: suggestion.message
            )
            
            try database.saveDecision(decision)
            
            logger.info("Successfully declined suggestion: \(suggestion.id)")
            return .success("Suggestion declined")
        } catch {
            logger.error("Failed to decline suggestion: \(error.localizedDescription)")
            return .failure(error.localizedDescription)
        }
    }
    
    // MARK: - Apply Suggestion Logic
    
    /// Apply the suggestion based on its type
    private func applySuggestion(_ suggestion: Suggestion) throws -> String {
        switch suggestion {
        case .profileChange(let profileSuggestion):
            return try applyProfileChange(profileSuggestion)
            
        case .zoneCreation(let zoneSuggestion):
            return try applyZoneCreation(zoneSuggestion)
            
        case .zoneDeletion(let zoneSuggestion):
            return try applyZoneDeletion(zoneSuggestion)
        }
    }
    
    private func applyProfileChange(_ suggestion: ProfileChangeSuggestion) throws -> String {
        guard let zone = try database.getZone(id: suggestion.zoneId) else {
            throw ApprovalError.zoneNotFound
        }
        
        guard var updatedProfile = try database.getProfile(id: zone.profileId) else {
            throw ApprovalError.profileNotFound
        }
        
        switch suggestion.suggestedSetting {
        case .dnd:
            updatedProfile.dnd = .on
            logger.info("Applying DND to profile for zone: \(zone.name)")
        case .vibrate:
            updatedProfile.vibrate = .on
            logger.info("Applying vibrate to profile for zone: \(zone.name)")
        case .automatic:
            logger.info("Automatic setting not fully implemented")
        case .on, .off:
            break
        }
        
        try database.updateProfile(updatedProfile)
        
        let updatedZone = Zone(
            id: zone.id,
            name: zone.name,
            latitude: zone.latitude,
            longitude: zone.longitude,
            radius: zone.radius,
            detectionMethods: zone.detectionMethods,
            profileId: updatedProfile.id
        )
        
        try database.updateZone(updatedZone)
        
        return "Profile updated: \(updatedProfile.name) - \(suggestion.suggestedSetting) enabled"
    }
    
    /// Apply a zone creation suggestion
    private func applyZoneCreation(_ suggestion: ZoneCreationSuggestion) throws -> String {
        // Create a new zone based on the suggestion
        // For now, create a default profile for the zone
        let newProfile = Profile(
            name: "Auto-created for \(suggestion.suggestedName)",
            ringtone: .off,
            vibrate: .off,
            unmute: .off,
            dnd: .off,
            alarms: .on,
            timers: .on
        )
        
        try database.createProfile(newProfile)
        
        let newZone = Zone(
            id: UUID(),
            name: suggestion.suggestedName,
            latitude: suggestion.latitude,
            longitude: suggestion.longitude,
            radius: suggestion.radius,
            detectionMethods: [.gps],
            profileId: newProfile.id
        )
        
        try database.createZone(newZone)
        
        logger.info("Created new zone: \(newZone.name) at (\(suggestion.latitude), \(suggestion.longitude))")
        
        return "Zone created: \(newZone.name) with profile: \(newProfile.name)"
    }
    
    /// Apply a zone deletion suggestion
    private func applyZoneDeletion(_ suggestion: ZoneDeletionSuggestion) throws -> String {
        // Get the zone to be deleted
        guard let zone = try database.getZone(id: suggestion.zoneId) else {
            throw ApprovalError.zoneNotFound
        }
        
        // Delete the zone
        try database.deleteZone(id: suggestion.zoneId)
        
        logger.info("Deleted zone: \(zone.name)")
        
        return "Zone deleted: \(zone.name)"
    }
    
    // MARK: - Decision History
    
    /// Get all decision history
    /// - Returns: Array of all decisions, sorted by timestamp (newest first)
    public func getDecisionHistory() -> [SuggestionDecision] {
        do {
            return try database.getAllDecisions()
        } catch {
            logger.error("Failed to get decision history: \(error.localizedDescription)")
            return []
        }
    }
    
    /// Get decision history for a specific time period
    /// - Parameter days: Number of days to look back
    /// - Returns: Array of decisions within the time period
    public func getRecentDecisions(days: Int) -> [SuggestionDecision] {
        do {
            return try database.getRecentDecisions(days: days)
        } catch {
            logger.error("Failed to get recent decisions: \(error.localizedDescription)")
            return []
        }
    }
    
    /// Get decisions for a specific suggestion type
    /// - Parameter type: The suggestion type to filter by
    /// - Returns: Array of decisions for that type
    public func getDecisions(for type: SuggestionType) -> [SuggestionDecision] {
        do {
            return try database.getDecisions(for: type)
        } catch {
            logger.error("Failed to get decisions for type \(type): \(error.localizedDescription)")
            return []
        }
    }
    
    // MARK: - Bulk Operations
    
    /// Approve multiple suggestions at once
    /// - Parameter suggestions: Array of suggestions to approve
    /// - Returns: Array of results for each suggestion
    public func approveMultiple(_ suggestions: [Suggestion]) -> [ApprovalResult] {
        return suggestions.map { approveSuggestion($0) }
    }
    
    /// Decline multiple suggestions at once
    /// - Parameter suggestions: Array of suggestions to decline
    /// - Returns: Array of results for each suggestion
    public func declineMultiple(_ suggestions: [Suggestion]) -> [ApprovalResult] {
        return suggestions.map { declineSuggestion($0) }
    }
    
    /// Clear all decision history (use with caution)
    public func clearHistory() {
        do {
            try database.clearAllDecisions()
            logger.info("Cleared all decision history")
        } catch {
            logger.error("Failed to clear decision history: \(error.localizedDescription)")
        }
    }
}

// MARK: - Supporting Types

/// Result of an approval or decline action
public enum ApprovalResult {
    case success(String)
    case failure(String)
    
    public var isSuccess: Bool {
        if case .success = self {
            return true
        }
        return false
    }
    
    public var message: String {
        switch self {
        case .success(let msg):
            return msg
        case .failure(let msg):
            return msg
        }
    }
}

/// Errors that can occur during approval
public enum ApprovalError: Error, LocalizedError {
    case zoneNotFound
    case profileNotFound
    case databaseError
    case invalidSuggestion
    
    public var errorDescription: String? {
        switch self {
        case .zoneNotFound:
            return "Zone not found"
        case .profileNotFound:
            return "Profile not found"
        case .databaseError:
            return "Database operation failed"
        case .invalidSuggestion:
            return "Invalid suggestion"
        }
    }
}

/// Represents a decision made on a suggestion
public struct SuggestionDecision: Codable, Identifiable {
    public let id: UUID
    public let suggestionId: UUID
    public let suggestionType: SuggestionType
    public let decision: DecisionType
    public let timestamp: Date
    public let suggestionMessage: String
    
    public init(
        id: UUID = UUID(),
        suggestionId: UUID,
        suggestionType: SuggestionType,
        decision: DecisionType,
        timestamp: Date,
        suggestionMessage: String
    ) {
        self.id = id
        self.suggestionId = suggestionId
        self.suggestionType = suggestionType
        self.decision = decision
        self.timestamp = timestamp
        self.suggestionMessage = suggestionMessage
    }
}

/// Type of decision made on a suggestion
public enum DecisionType: String, Codable {
    case approved
    case declined
}